[package]
name = "rust-parameters-lambda-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
tokio = { version = "1.15.0", features = ["full"] }
futures = { version = "0.3.19" }

serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.75"

aws-types = "0.4.1"
aws-config = "0.4.1"
aws-sdk-dynamodb = "0.4.1"
aws-sdk-ssm = "0.4.1"

lambda_runtime = "0.4.1"
lambda_extension = { git = "https://github.com/awslabs/aws-lambda-rust-runtime" }

axum = "0.4.4"
tower = "0.4.11"
tower-http = { version = "0.2.1", features = ["add-extension"] }